{{- if .Values.enableMessageQueue }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nx-cloud-messagequeue
  labels:
    app: nx-cloud-messagequeue
    {{- include "nxCloud.app.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nx-cloud-messagequeue
  template:
    metadata:
      labels:
        app: nx-cloud-messagequeue
    spec:
      containers:
        - name: nx-cloud-messagequeue
          image: nxprivatecloud/nx-cloud-messagequeue:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 61616
              name: tcp
          volumeMounts:
            - mountPath: /opt/activemq/data
              name: data
      volumes:
        - emptyDir: {}
          name: data
{{- end }}