---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nx-cloud-api
  labels:
    {{- include "nxCloud.app.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas.api }}
  selector:
    matchLabels:
      app: nx-cloud-api
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nx-cloud-api
    spec:
      containers:
        - name: nx-cloud-api
          image: {{ include "nxCloud.images.api.image" . }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy | quote }}
          {{- if .Values.api.resources }}
          resources: {{- toYaml .Values.api.resources | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 4000
          {{- if not .Values.api.skipLiveness }}
          livenessProbe:
            httpGet:
              path: /api/uptime-check
              port: 4000
            initialDelaySeconds: 20
          startupProbe:
            httpGet:
              path: /api/uptime-check
              port: 4000
            initialDelaySeconds: 5
            failureThreshold: 5
            periodSeconds: 10
          {{- end}}
          {{- if .Values.selfSignedCertConfigMap }}
          volumeMounts:
            - mountPath: /self-signed-certs
              name: self-signed-certs-volume
          {{- end}}
          env:
            {{- if .Values.selfSignedCertConfigMap }}
            - name: NODE_EXTRA_CA_CERTS
              value: /self-signed-certs/self-signed-cert.crt
            {{- end}}
          {{- include "nxCloud.env.nxCloudAppUrl" . | indent 12 }}
          {{- include "nxCloud.env.mongoSecrets" . | indent 12 }}
          {{- include "nxCloud.env.mode" . | indent 12 }}
          {{- include "nxCloud.env.verboseLogging" . | indent 12 }}
          {{- with .Values.secret }}
            {{- if .name }}
              {{- if .githubPrivateKey }}
            - name: NX_CLOUD_GITHUB_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}
                  key: {{ .githubPrivateKey }}
              {{- end }}
              {{- if .githubAppId }}
            - name: NX_CLOUD_GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}
                  key: {{ .githubAppId }}
              {{- end }}
              {{- if .hubspotApiKey }}
            - name: HUBSPOT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}
                  key: {{ .hubspotApiKey }}
              {{- end }}
            {{- else }}
              {{- if .githubPrivateKey }}
            - name: SECRET_FILE_NX_CLOUD_GITHUB_PRIVATE_KEY
              value: {{ .githubPrivateKey }}
              {{- end }}
              {{- if .githubAppId }}
            - name: SECRET_FILE_NX_CLOUD_GITHUB_APP_ID
              value: {{ .githubAppId }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- if .Values.saml }}
          {{- if .Values.saml.enabled }}
          {{- if .Values.secret.name }}
            - name: SAML_CERT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.samlCert }}
            - name: SAML_ENTRY_POINT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.samlEntryPoint }}
          {{- else }}
            - name: SAML_CERT
              value: {{ .Values.secret.samlCert }}
            - name: SAML_ENTRY_POINT
              value: {{ .Values.secret.samlEntryPoint }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if .Values.github }}
          {{- if .Values.github.auth }}
          {{- if .Values.github.auth.enabled }}
          {{- if .Values.secret.name }}
            - name: GITHUB_AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.githubAuthClientId }}
            - name: GITHUB_AUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.githubAuthClientSecret }}
          {{- else }}
            - name: SECRET_FILE_GITHUB_AUTH_CLIENT_ID
              value: {{ .Values.secret.githubAuthClientId }}
            - name: SECRET_FILE_GITHUB_AUTH_CLIENT_SECRET
              value: {{ .Values.secret.githubAuthClientSecret }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if .Values.addonUnlockKey }}
            - name: NX_CLOUD_ADDON_KEY
              value: '{{ .Values.addonUnlockKey }}'
          {{- end }}
          {{- if .Values.useCosmosDb }}
            - name: NX_CLOUD_USE_MONGO42
              value: 'false'
          {{- end }}
      {{- if .Values.selfSignedCertConfigMap }}
      volumes:
        - configMap:
            name: {{ .Values.selfSignedCertConfigMap }}
          name: self-signed-certs-volume
      {{- end }}