apiVersion: apps/v1
kind: Deployment
metadata:
  name: nx-cloud-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nxCloud.mergedLabels" (dict "resourceLabels" .Values.frontend.deployment.labels "context" .) | nindent 4 }}
  {{- with .Values.frontend.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.frontend.deployment.replicas | default 1}}
  selector:
    matchLabels:
      {{- include "nxCloud.selectorLabels" (dict "component" "nx-cloud-frontend" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 12 }}
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  {{- with .Values.frontend.deployment.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "nxCloud.selectorLabels" (dict "component" "nx-cloud-frontend" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 8 }}
        {{- with .Values.global.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.frontend.deployment.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.frontend.serviceAccount.name }}
      {{- if .Values.frontend.deployment.volumes }}
      volumes:
        {{- toYaml .Values.frontend.deployment.volumes | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: nx-cloud-frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Values.global.imageTag }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy | default .Values.global.imagePullPolicy }}
          {{- if .Values.frontend.deployment.resources }}
          resources: {{- toYaml .Values.frontend.deployment.resources | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4202
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 4202
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 4202
          env:
            - name: NX_CLOUD_MODE
              value: 'private-enterprise'
            - name: NX_CLOUD_APP_URL
              value: {{ .Values.global.nxCloudAppURL }}
            {{- if .Values.global.mongodbConnectionString.secretName }}
            - name: NX_CLOUD_MONGO_SERVER_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.mongodbConnectionString.secretName }}
                  key: {{ .Values.global.mongodbConnectionString.secretKey }}
            {{- end }}
            {{- if .Values.frontend.verboseLogging | default .Values.global.verboseLogging }}
            - name: NX_VERBOSE_LOGGING
              value: "true"
            {{- end }}
            - name: NX_API_LOG_LEVEL
              value: {{ .Values.frontend.logLevel | default .Values.global.logLevel | quote }}
            {{- range $key, $value := .Values.frontend.deployment.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.frontend.deployment.envValueFrom }}
            - name: {{ $key }}
              valueFrom:
                {{- toYaml $value | nindent 16 }}
            {{- end }}
          {{- if .Values.frontend.deployment.envFrom }}
          envFrom:
            {{- toYaml .Values.frontend.deployment.envFrom | nindent 12 }}
          {{- end }}
          {{- if .Values.frontend.deployment.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.frontend.deployment.volumeMounts | nindent 12 }}
          {{- end }}
          {{- if .Values.frontend.deployment.securityContext }}
          securityContext:
          {{- omit .Values.frontend.deployment.securityContext "fsGroup" "fsGroupChangePolicy" | toYaml | nindent 12 }}
          {{- end }}
